version: '3.8'

services:
  # Servidor de arquivos
  fileserver:
    build: ./fileserver
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=4000
    volumes:
      - ./fileserver/uploads:/app/uploads
    restart: unless-stopped

  # Aplicação principal Next.js
  nextapp:
    build: .
    ports:
      - '3000:3000'
    environment:
      # Ambiente e banco
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      
      # URLs do sistema
      - APP_URL=${APP_URL:-http://localhost:3000}
      - FILESERVER_URL=${FILESERVER_URL:-http://localhost:4000}
      
      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      
      # Email SMTP
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

    depends_on:
      - fileserver
    restart: unless-stopped
