version: '3.8'

services:
  # Servidor de arquivos
  fileserver:
    build: ./fileserver
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
    volumes:
      - ./fileserver/uploads:/app/uploads
    restart: unless-stopped

  # Aplicação principal
  nextapp:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - fileserver
    restart: unless-stopped
